# Due to hard dependencies to the TA-dev-kit (especially conf.cmake generated by
# optee_os included by optee_test/host/xtest/CMakefileLists.txt), it's not
# possible to build only using CMake. This makefile is a step in the right
# direction. It builds OP-TEE OS optee_test using GNU Make. Everything else
# builds using CMake (TA's in xtest piggy back on old makefile).

# Must have Arm toolchain on the PATH
export PATH 	?= $(HOME)/toolchains/aarch32/bin:$(HOME)/toolchains/aarch64/bin:$(PATH)

ARCH		?= arm32
PLATFORM	?= vexpress
PLATFORM_FLAVOR	?= qemu_virt

CMAKE_OUT 	?= $(CURDIR)/out
CMAKE_FLAGS 	?= -DCFG_TA_MBEDTLS=n \
		   -DOPTEE_TEST_SDK=$(TA_DEV_KIT) \
		   -DARCH=$(ARCH) \
		   -DPLATFORM=$(PLATFORM) \
		   -DPLATFORM_FLAVOR=$(PLATFORM_FLAVOR)

OPTEE_OUT	?= $(CURDIR)/optee_os/out
OPTEE_FLAGS	?= CFG_TA_MBEDTLS=n \
		   CFG_TA_MBEDTLS_MPI=n \
		   PLATFORM=$(PLATFORM) \
		   PLATFORM_FLAVOR=$(PLATFORM_FLAVOR)

TA_DEV_KIT	?= $(OPTEE_OUT)/arm-plat-$(PLATFORM)/export-ta_$(ARCH)

all: optee-os optee-cmake

.PHONY: optee-cmake
optee-cmake: optee-os
	mkdir -p $(CMAKE_OUT) && \
	cd $(CMAKE_OUT) && \
	cmake $(CMAKE_FLAGS) .. && \
	make

.PHONY: optee-os
optee-os:
	make -C $(CURDIR)/optee_os $(OPTEE_FLAGS)

.PHONY: clean
clean:
	cd $(CURDIR)/optee_os && git clean -xdf && \
		rm -rf $(CMAKE_OUT)
